### ISSUE TITLE
Document is not defined

### ISSUE THREAD

**Issue by IsmaeelAkram** [sidneys/electron-titlebar-windows#15]
Can you please tell me how you even got the bar to work? The docs aren't very good. It says document is not defined.

**Comment by tessamerrill** [comment]
How did you solve it?

**Comment by IsmaeelAkram** [comment]
Put all the code in the browser JS files and enable nodeIntegration in BrowserWindow settings.

**Comment by DRISHTANT-DUBEY** [comment]
I got this error even after nodeIntegration enabling ❌
